language: perl
perl:
   - "5.10"
   - "5.12"
   - "5.14"
   - "5.16"
   - "5.18"

before_install:
    # gotta love failing pod tests blowing everything up...
    - cpanm -q TAP::Harness::Restricted || { cat ~/.cpanm/build.log ; false ; }

    # git bits sometimes needed...  Again?!
    - git config --global user.name 'Travis-CI'
    - git config --global user.email 'travis@nowhere.dne'

    # not so much install our package as all its prereqs
    - HARNESS_SUBCLASS=TAP::Harness::Restricted cpanm -q --installdeps . || { cat ~/.cpanm/build.log ; false ; }

install:
    # NOOP, really
    - true

script:
    - prove -lr t/
